In [ ]:
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
csv_path = "/content/drive/MyDrive/Fake News Project"

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Fake News Project/train.csv")

In [ ]:
x = df.drop("label", axis = 1)
y = df["label"]

In [ ]:
voc_size = 5000

In [ ]:
messages = x.copy()

In [ ]:
messages.reset_index(inplace = True)
messages.head()

index  id                                              title  \
0      0   0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1      1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2   2                  Why the Truth Might Get You Fired   
3      3   3  15 Civilians Killed In Single US Airstrike Hav...   
4      4   4  Iranian woman jailed for fictional unpublished...   

               author                                               text  
0       Darrell Lucus  House Dem Aide: We Didn’t Even See Comey’s Let...  
1     Daniel J. Flynn  Ever get the feeling your life circles the rou...  
2  Consortiumnews.com  Why the Truth Might Get You Fired October 29, ...  
3     Jessica Purkiss  Videos 15 Civilians Killed In Single US Airstr...  
4      Howard Portnoy  Print \nAn Iranian woman has been sentenced to...

In [ ]:
import nltk

In [ ]:
import re

In [ ]:
from nltk.corpus import stopwords

In [ ]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', str(messages['title'][i]))
    #review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
15800
15801
15802
15803
15804
15805
15806
15807
15808
15809
15810
15811
15812
15813
15814
15815
15816
15817
15818
15819
15820
15821
15822
15823
15824
15825
15826
15827
15828
15829
15830
15831
15832
15833
15834
15835
15836
15837
15838
15839
15840
15841
15842
15843
15844
15845
15846
15847
15848
15849
15850
15851
15852
15853
15854
15855
15856
15857
15858
15859
15860
15861
15862
15863
15864
15865
15866
15867
15868
15869
15870
15871
15872
15873
15874
15875
15876
15877
15878
15879
15880
15881
15882
15883
15884
15885
15886
15887
15888
15889
15890
15891
15892
15893
15894
15895
15896
15897
15898
15899
15900
15901
15902
15903
15904
15905
15906
15907
15908
15909
15910
15911
15912
15913
15914
15915
15916
15917
15918
15919
15920
15921
15922
15923
15924
15925
15926
15927
15928
15929
15930
15931
15932
15933
15934
15935
15936
15937
15938
15939
15940
15941
15942
15943
15944
15945
15946
15947
15948
15949
15950
15951
15952
15953
15954
15955
15956
15957
1

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[492, 3164, 2812, 3907, 4192, 1305, 2883, 3865, 2402, 3934],
 [1218, 1127, 1965, 2647, 1704, 2290, 4711],
 [979, 2761, 2020, 705],
 [4675, 621, 408, 4973, 638, 2854],
 [1603, 1704, 1477, 9, 433, 2583, 1704, 1640, 4120, 3139],
 [4432,
  2210,
  379,
  4251,
  28,
  4226,
  3302,
  2089,
  1069,
  1580,
  2503,
  1421,
  4401,
  1623,
  4711],
 [165, 165, 1925, 4302, 3201, 2457, 2246, 1250, 4291, 2408, 2269, 307],
 [1906, 2802, 165, 1354, 4581, 430, 1055, 3503, 1115, 3690, 4079],
 [2445, 4903, 1459, 1454, 4226, 4526, 73, 4105, 4338, 3079, 1115, 3690, 4079],
 [4002, 3725, 2408, 2153, 4333, 1021, 4226, 310, 1115, 3690, 4079],
 [4572, 4639, 4926, 4690, 1672, 2816, 622, 1127, 4226, 2933],
 [734, 3278, 916, 4917, 1675, 2094, 2534, 4004],
 [1787, 4912, 4239, 938, 3297, 2247, 1049, 1732, 1799, 1637, 425],
 [4973, 2688, 4192, 2816, 4226, 4333],
 [297, 3202, 1666, 4588, 780, 140, 2705, 610, 2526],
 [3777, 4303, 967, 3009, 3085, 2214, 324, 1115, 3690, 4079],
 [2367, 471, 2548, 2800, 389, 1115, 36

In [ ]:
sent_length = 20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 3865 2402 3934]
 [   0    0    0 ... 1704 2290 4711]
 [   0    0    0 ... 2761 2020  705]
 ...
 [   0    0    0 ... 1115 3690 4079]
 [   0    0    0 ... 3910 1660 1617]
 [   0    0    0 ...  356  711 1528]]


In [ ]:
#creating model
from tensorflow.keras.layers import Dropout
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation="sigmoid"))
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 20, 40)            200000    
                                                                 
 dropout_2 (Dropout)         (None, 20, 40)            0         
                                                                 
 lstm_1 (LSTM)               (None, 100)               56400     
                                                                 
 dropout_3 (Dropout)         (None, 100)               0         
                                                                 
 dense_1 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
x_final = np.array(embedded_docs)
y_final = np.array(y)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_final,y_final, test_size=0.33, random_state = 42)

In [ ]:
#model Training
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
218/218 [==============================] - 9s 9ms/step - loss: 0.3265 - accuracy: 0.8479 - val_loss: 0.1902 - val_accuracy: 0.9234
Epoch 2/10
218/218 [==============================] - 2s 7ms/step - loss: 0.1392 - accuracy: 0.9442 - val_loss: 0.1780 - val_accuracy: 0.9264
Epoch 3/10
218/218 [==============================] - 2s 7ms/step - loss: 0.1047 - accuracy: 0.9610 - val_loss: 0.1848 - val_accuracy: 0.9289
Epoch 4/10
218/218 [==============================] - 2s 7ms/step - loss: 0.0805 - accuracy: 0.9727 - val_loss: 0.2189 - val_accuracy: 0.9247
Epoch 5/10
218/218 [==============================] - 2s 7ms/step - loss: 0.0622 - accuracy: 0.9793 - val_loss: 0.2519 - val_accuracy: 0.9193
Epoch 6/10
218/218 [==============================] - 2s 7ms/step - loss: 0.0487 - accuracy: 0.9854 - val_loss: 0.2539 - val_accuracy: 0.9296
Epoch 7/10
218/218 [==============================] - 2s 7ms/step - loss: 0.0358 - accuracy: 0.9882 - val_loss: 0.2683 - val_accuracy: 0.9282
Epoch 

In [ ]:
y_pred = model.predict(x_test).round()
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

215/215 [==============================] - 0s 2ms/step


array([[3155,  294],
       [ 231, 3184]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.923513986013986